=== omwro/AlgorithmsDataStructuresAssignments/Supermarket/src/main/resources/supermarket.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="supermarket">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="products" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="customers" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="openTime" type="xs:time" use="required"/>
            <xs:attribute name="closingTime" type="xs:time" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" type="ProductType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="ProductType">
        <xs:attribute name="code" type="xs:NCName" use="required"/>
        <xs:attribute name="description" type="xs:string" use="optional"/>
        <xs:attribute name="price" type="xs:decimal" use="required"/>
    </xs:complexType>
    <xs:element name="customers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="customer" type="CustomerType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="CustomerType">
        <xs:sequence>
            <xs:element name="purchase" type="PurchaseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="queuedAt" type="xs:time" use="required"/>
        <xs:attribute name="zipCode" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="PurchaseType">
        <xs:attribute name="product" type="xs:NCName" use="required"/>
        <xs:attribute name="amount" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
</xs:schema>

=== omwro/AlgorithmsDataStructuresAssignments/Supermarket/src/main/resources/jambi5.xml
<?xml version="1.0" ?>
<supermarket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="supermarket.xsd" 
	openTime="12:00:00" closingTime="12:05:00">
  <products>
    <product code="LEV001" description="Calve Pindakaas 650g" price="6.35"></product>
    <product code="ZUI003" description="Verse scharreleieren 4 stuks" price="1.26"></product>
    <product code="BRO001" description="Croissant" price="0.50"></product>
    <product code="SCH001" description="Robijn stralend wit" price="6.85"></product>
    <product code="VOE001" description="Douwe Egberts snelfilter 500g" price="4.25"></product>
  </products>
  <customers>
    <customer queuedAt="12:00:32" zipCode="1015DP">
      <purchase product="BRO001" amount="2"></purchase>
      <purchase product="SCH001" amount="1"></purchase>
    </customer>
    <customer queuedAt="12:00:28" zipCode="1015DK">
      <purchase product="LEV001" amount="5"></purchase>
    </customer>
    <customer queuedAt="12:01:51" zipCode="1014DA">
      <purchase product="ZUI003" amount="1"></purchase>
      <purchase product="LEV001" amount="5"></purchase>
      <purchase product="SCH001" amount="2"></purchase>
    </customer>
    <customer queuedAt="12:00:18" zipCode="1014DA">
      <purchase product="ZUI003" amount="8"></purchase>
    </customer>
    <customer queuedAt="12:04:23" zipCode="1016DK">
    </customer>
    <customer queuedAt="12:00:39" zipCode="1015DK">
      <purchase product="LEV001" amount="1"></purchase>
    </customer>
  </customers>
</supermarket>

=== omwro/AlgorithmsDataStructuresAssignments/Supermarket/src/main/resources/jambi2.xml
<?xml version="1.0" ?>
<supermarket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="supermarket.xsd" 
	openTime="12:00:00" closingTime="12:05:00">
  <products>
    <product code="LEV001" description="Calve Pindakaas 650g" price="6.35"></product>
    <product code="ZUI003" description="Verse scharreleieren 4 stuks" price="1.26"></product>
    <product code="BRO001" description="Croissant" price="0.50"></product>
    <product code="SCH001" description="Robijn stralend wit" price="6.85"></product>
    <product code="VOE001" description="Douwe Egberts snelfilter 500g" price="4.25"></product>
  </products>
  <customers>
    <customer queuedAt="12:04:14" zipCode="1013MF">
      <purchase product="BRO001" amount="1"></purchase>
    </customer>
    <customer queuedAt="12:03:58" zipCode="1013MF">
      <purchase product="BRO001" amount="1"></purchase>
      <purchase product="VOE001" amount="1"></purchase>
    </customer>
  </customers>
</supermarket>

=== omwro/AlgorithmsDataStructuresAssignments/Supermarket/src/main/resources/supermarket25.xml
<?xml version="1.0" ?>
<supermarket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="supermarket.xsd"
             openTime="12:00:00" closingTime="12:30:00">
    <products>
        <product code="BRO001" description="Croissant" price="0.50"/>
        <product code="BRO002" description="Kaiser broodje" price="0.35"/>
        <product code="BRO003" description="Zaanse snijder heel" price="1.28"/>
        <product code="ZUI001" description="Campina halfvolle melk 1L" price="0.76"/>
        <product code="ZUI002" description="Campina magere yoghurt 1.5L" price="1.35"/>
        <product code="ZUI003" description="Verse scharreleieren 4 stuks" price="1.26"/>
        <product code="ZUI004" description="Old Amsterdam stuk 1Kg" price="8.26"/>
        <product code="LEV001" description="Calve Pindakaas 650g" price="6.35"/>
        <product code="LEV002" description="Bonne Maman aardbeienjam" price="3.65"/>
        <product code="VLE001" description="Kip kilo knaller" price="4.85"/>
        <product code="VLE002" description="Filetlapjes 700g" price="3.85"/>
        <product code="VLE003" description="Eendeborst 500g" price="19.85"/>
        <product code="GRO001" description="Paprika" price="0.75"/>
        <product code="GRO002" description="Bloemkool" price="1.00"/>
        <product code="GRO003" description="Aardappelen vastkokend 2.5Kg" price="2.09"/>
        <product code="SNA001" description="Cashew noten 300g" price="3.85"/>
        <product code="SNA002" description="Studentenhaver 300g" price="3.85"/>
        <product code="DRA002" description="Hertog Jan 6-pack" price="4.85"/>
        <product code="DRA003" description="Coca Cola Zero 1.5L" price="1.46"/>
        <product code="DRA004" description="Multivruchtensap 2L" price="2.81"/>
        <product code="SCH001" description="Robijn stralend wit" price="6.85"/>
        <product code="SCH002" description="Robijn kleur en fijn" price="8.85"/>
        <product code="VOE001" description="Douwe Egberts snelfilter 500g" price="4.25"/>
        <product code="DIE001" description="Gourmet tonijn 100g" price="0.85"/>
        <product code="DIE002" description="Purina kip adult 1.5Kg" price="13.25"/>
    </products>
</supermarket>
